# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ungitz < Formula
  desc ""
  homepage "https://github.com/hrshankar2002/ungitz"
  version "1.2"

  on_macos do
    url "https://github.com/hrshankar2002/ungitz/releases/download/v1.2/ungitz_1.2_darwin_all.tar.gz"
    sha256 "c999db6585b054605f3adaff0186a69dad0a0697082da56d35e09229b3bb7b81"

    def install
      bin.install "ungitz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hrshankar2002/ungitz/releases/download/v1.2/ungitz_1.2_linux_arm64.tar.gz"
      sha256 "373ea2859332d94302846dcdb9ad9c9ce4b6a955d0142b4021f4cb0665cdaf77"

      def install
        bin.install "ungitz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hrshankar2002/ungitz/releases/download/v1.2/ungitz_1.2_linux_amd64.tar.gz"
      sha256 "3b043008c03af4ad0362f802b28624d52fd45144cade7cb966da9da2f3861dd4"

      def install
        bin.install "ungitz"
      end
    end
  end
end
