# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ungitz < Formula
  desc ""
  homepage "https://github.com/hrshankar2002/ungitz"
  version "1.2"

  on_macos do
    url "https://github.com/hrshankar2002/ungitz/releases/download/v1.2/ungitz_1.2_darwin_all.tar.gz"
    sha256 "2c46bb5d532691fd4a10d90eba2412537ebcb26864e917ca8d11793964518e2f"

    def install
      bin.install "ungitz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hrshankar2002/ungitz/releases/download/v1.2/ungitz_1.2_linux_arm64.tar.gz"
      sha256 "18307bc166e667d12e5356f87a7fccae47e71b25aa2521a6873b96384ee1202e"

      def install
        bin.install "ungitz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hrshankar2002/ungitz/releases/download/v1.2/ungitz_1.2_linux_amd64.tar.gz"
      sha256 "5b30d1788c3e953c7cb8219a9325758170e168a0dac20f677aa90f5227c7808e"

      def install
        bin.install "ungitz"
      end
    end
  end
end
