# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ungitz < Formula
  desc ""
  homepage "https://github.com/hrshankar2002/ungitz"
  version "1.1"

  on_macos do
    url "https://github.com/hrshankar2002/ungitz/releases/download/v1.1/ungitz_1.1_darwin_all.tar.gz"
    sha256 "a64d60218c7390b9ec035319b57f3e85d80ef2f9c812d3c6e8f16e66dc061915"

    def install
      bin.install "ungitz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hrshankar2002/ungitz/releases/download/v1.1/ungitz_1.1_linux_arm64.tar.gz"
      sha256 "860e342c782a419d68fb7547783ecd02aaba6f50040ca8171c8a9deed83ca333"

      def install
        bin.install "ungitz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hrshankar2002/ungitz/releases/download/v1.1/ungitz_1.1_linux_amd64.tar.gz"
      sha256 "66219cb303cb8ca4ef89c8164cee3a9b1916d162114b3049e63a66538e125cd9"

      def install
        bin.install "ungitz"
      end
    end
  end
end
